# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	
	config.vm.box = "ubuntu/xenial64"
	config.vm.hostname = "docker-host"

	config.vm.provision "ansible_local" do |ansible|
		ansible.playbook = "playbook.yml"
		ansible.raw_arguments = [
			"--extra-vars",
			"docker_file_path=/vagrant/containers"
		]
	end

end
